"""Export the real bilinear-interpolated wind field (pipeline/downscale.bilinear_box,
the same function app.py's 5 km panel uses) for every step of every case's main track,
on a fixed-size grid so the dashboard's ZoomCanvas can render genuine interpolated
values instead of a synthetic illustrative shape.

    python scripts/export_zoom_fields.py

Writes dashboard-ui/src/data/zoomFields.js, keyed by case id -> lead hour (t) -> a
flat N x N array of wind speed (m/s), plus its co-ordinate bounds.
"""
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import xarray as xr

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from pipeline.downscale import bilinear_box  # noqa: E402

PROC = ROOT / "data" / "processed"
OUT = ROOT / "dashboard-ui" / "src" / "data" / "zoomFields.js"
GRID_N = 36  # fixed display grid, independent of each object's box size


def fixed_grid_interp(field2d, lat, lon, box, n=GRID_N):
    from scipy.interpolate import RegularGridInterpolator
    lat_min, lat_max, lon_min, lon_max = box
    lat_min, lat_max = max(lat_min, lat[0]), min(lat_max, lat[-1])
    lon_min, lon_max = max(lon_min, lon[0]), min(lon_max, lon[-1])
    fine_lat = np.linspace(lat_min, lat_max, n)
    fine_lon = np.linspace(lon_min, lon_max, n)
    f = RegularGridInterpolator((lat, lon), field2d, method="linear")
    LAT, LON = np.meshgrid(fine_lat, fine_lon, indexing="ij")
    return f(np.stack([LAT, LON], axis=-1))


def export_case(key):
    d = PROC / key
    if not (d / "fields.nc").exists():
        return None
    val = json.loads((d / "validation.json").read_text())
    tracks = json.loads((d / "tracks.json").read_text())
    main = next((tr for tr in tracks if tr["track_id"] == val["track_id"]), None)
    if main is None:
        return None
    ds = xr.open_dataset(d / "fields.nc")
    lat, lon = ds.lat.values, ds.lon.values
    times = pd.to_datetime(ds.time.values)
    t0 = pd.Timestamp(main["points"][0]["time"])

    out = {}
    for p in main["points"]:
        t = pd.Timestamp(p["time"])
        lead_h = int(round((t - t0).total_seconds() / 3600))
        idx = int(np.argmin(np.abs(times - t)))
        box = (p["lat_min"], p["lat_max"], p["lon_min"], p["lon_max"])
        grid = fixed_grid_interp(ds.ws.isel(time=idx).values, lat, lon, box)
        out[str(lead_h)] = {
            "box": [round(box[0], 3), round(box[1], 3), round(box[2], 3), round(box[3], 3)],
            "grid": [round(float(v), 1) for v in grid.ravel()],
        }
    ds.close()
    return out


def main():
    cases = {}
    for d in sorted(PROC.iterdir()):
        if d.is_dir() and (d / "fields.nc").exists():
            rec = export_case(d.name)
            if rec:
                cases[d.name] = rec
                print(f"  {d.name}: {len(rec)} steps x {GRID_N}x{GRID_N}")
    OUT.write_text(
        "// Real bilinear-interpolated wind field (pipeline/downscale.bilinear_box, the same\n"
        "// function app.py's 5 km panel uses) for every step of every case's main track, on a\n"
        f"// fixed {GRID_N}x{GRID_N} display grid. Generated by scripts/export_zoom_fields.py --\n"
        "// nothing here is synthetic. grid is row-major over [box[0]..box[1]] lat x [box[2]..box[3]] lon.\n\n"
        f"export const ZOOM_GRID_N = {GRID_N}\n\n"
        f"export const ZOOM_FIELDS = {json.dumps(cases)}\n"
    )
    total = sum(len(v) for v in cases.values())
    print(f"wrote {OUT} ({len(cases)} cases, {total} steps total)")
    print(f"file size: {OUT.stat().st_size / 1024:.0f} KB")


if __name__ == "__main__":
    main()
